name: slurm build
on: [push, pull_request]
jobs:
  build-gcc:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.0.0
      - run: sudo apt-get install cmake libmunge-dev liblua5.2-dev munge expect libhwloc-dev libnuma1 libnuma-dev libpam-dev libpam-dev gdb valgrind libfreeipmi-dev man2html
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
