/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/home/ubuntu/ScSFWorkerForSlurm-0.1/slurm_install/slurm_varios/lib/slurm";
char *default_slurm_config_file = "/home/ubuntu/ScSFWorkerForSlurm-0.1/slurm_install/slurm_conf/slurm.conf";
char *default_plugstack = "/home/ubuntu/ScSFWorkerForSlurm-0.1/slurm_install/slurm_conf/plugstack.conf";
