/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/media/sf_workspace/SIMULATOR_git/slurm_install/slurm_varios/lib/slurm";
char *default_slurm_config_file = "/media/sf_workspace/SIMULATOR_git/slurm_install/slurm_conf/slurm.conf";
char *default_plugstack = "/media/sf_workspace/SIMULATOR_git/slurm_install/slurm_conf/plugstack.conf";
